// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: disp.proto

package ss

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//
//Target Server Type
type DISP_MSG_TARGET int32

const (
	DISP_MSG_TARGET_NON_SERVER   DISP_MSG_TARGET = 0 //no target type specified
	DISP_MSG_TARGET_LOGIC_SERVER DISP_MSG_TARGET = 1
	DISP_MSG_TARGET_CHAT_SERVER  DISP_MSG_TARGET = 2
)

// Enum value maps for DISP_MSG_TARGET.
var (
	DISP_MSG_TARGET_name = map[int32]string{
		0: "NON_SERVER",
		1: "LOGIC_SERVER",
		2: "CHAT_SERVER",
	}
	DISP_MSG_TARGET_value = map[string]int32{
		"NON_SERVER":   0,
		"LOGIC_SERVER": 1,
		"CHAT_SERVER":  2,
	}
)

func (x DISP_MSG_TARGET) Enum() *DISP_MSG_TARGET {
	p := new(DISP_MSG_TARGET)
	*p = x
	return p
}

func (x DISP_MSG_TARGET) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DISP_MSG_TARGET) Descriptor() protoreflect.EnumDescriptor {
	return file_disp_proto_enumTypes[0].Descriptor()
}

func (DISP_MSG_TARGET) Type() protoreflect.EnumType {
	return &file_disp_proto_enumTypes[0]
}

func (x DISP_MSG_TARGET) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DISP_MSG_TARGET.Descriptor instead.
func (DISP_MSG_TARGET) EnumDescriptor() ([]byte, []int) {
	return file_disp_proto_rawDescGZIP(), []int{0}
}

//
//Choose Target Server Method
type DISP_MSG_METHOD int32

const (
	DISP_MSG_METHOD_RAND DISP_MSG_METHOD = 0
	DISP_MSG_METHOD_HASH DISP_MSG_METHOD = 1
	DISP_MSG_METHOD_SPEC DISP_MSG_METHOD = 2 //sepcify target
)

// Enum value maps for DISP_MSG_METHOD.
var (
	DISP_MSG_METHOD_name = map[int32]string{
		0: "RAND",
		1: "HASH",
		2: "SPEC",
	}
	DISP_MSG_METHOD_value = map[string]int32{
		"RAND": 0,
		"HASH": 1,
		"SPEC": 2,
	}
)

func (x DISP_MSG_METHOD) Enum() *DISP_MSG_METHOD {
	p := new(DISP_MSG_METHOD)
	*p = x
	return p
}

func (x DISP_MSG_METHOD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DISP_MSG_METHOD) Descriptor() protoreflect.EnumDescriptor {
	return file_disp_proto_enumTypes[1].Descriptor()
}

func (DISP_MSG_METHOD) Type() protoreflect.EnumType {
	return &file_disp_proto_enumTypes[1]
}

func (x DISP_MSG_METHOD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DISP_MSG_METHOD.Descriptor instead.
func (DISP_MSG_METHOD) EnumDescriptor() ([]byte, []int) {
	return file_disp_proto_rawDescGZIP(), []int{1}
}

//
// Disp Proto <serv1 -- disp -- serv2>
// Add Proto Should also modify servers/comm/disp.go:GenDispMsg and ExDispMsg functions
type DISP_PROTO_TYPE int32

const (
	DISP_PROTO_TYPE_HELLO               DISP_PROTO_TYPE = 0
	DISP_PROTO_TYPE_KICK_DUPLICATE_USER DISP_PROTO_TYPE = 1 //kick duplicate user on other line
)

// Enum value maps for DISP_PROTO_TYPE.
var (
	DISP_PROTO_TYPE_name = map[int32]string{
		0: "HELLO",
		1: "KICK_DUPLICATE_USER",
	}
	DISP_PROTO_TYPE_value = map[string]int32{
		"HELLO":               0,
		"KICK_DUPLICATE_USER": 1,
	}
)

func (x DISP_PROTO_TYPE) Enum() *DISP_PROTO_TYPE {
	p := new(DISP_PROTO_TYPE)
	*p = x
	return p
}

func (x DISP_PROTO_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DISP_PROTO_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_disp_proto_enumTypes[2].Descriptor()
}

func (DISP_PROTO_TYPE) Type() protoreflect.EnumType {
	return &file_disp_proto_enumTypes[2]
}

func (x DISP_PROTO_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DISP_PROTO_TYPE.Descriptor instead.
func (DISP_PROTO_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_disp_proto_rawDescGZIP(), []int{2}
}

//DispMsg
type MsgDisp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtoType  DISP_PROTO_TYPE `protobuf:"varint,1,opt,name=proto_type,json=protoType,proto3,enum=ss.DISP_PROTO_TYPE" json:"proto_type,omitempty"`
	Target     DISP_MSG_TARGET `protobuf:"varint,2,opt,name=target,proto3,enum=ss.DISP_MSG_TARGET" json:"target,omitempty"`
	Method     DISP_MSG_METHOD `protobuf:"varint,3,opt,name=method,proto3,enum=ss.DISP_MSG_METHOD" json:"method,omitempty"`
	SpecServer int32           `protobuf:"varint,4,opt,name=spec_server,json=specServer,proto3" json:"spec_server,omitempty"` //only for METHOD_SPEC
	FromServer int32           `protobuf:"varint,5,opt,name=from_server,json=fromServer,proto3" json:"from_server,omitempty"`
	// Types that are assignable to DispBody:
	//	*MsgDisp_Hello
	//	*MsgDisp_KickDupUser
	DispBody isMsgDisp_DispBody `protobuf_oneof:"disp_body"`
}

func (x *MsgDisp) Reset() {
	*x = MsgDisp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_disp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgDisp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDisp) ProtoMessage() {}

func (x *MsgDisp) ProtoReflect() protoreflect.Message {
	mi := &file_disp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDisp.ProtoReflect.Descriptor instead.
func (*MsgDisp) Descriptor() ([]byte, []int) {
	return file_disp_proto_rawDescGZIP(), []int{0}
}

func (x *MsgDisp) GetProtoType() DISP_PROTO_TYPE {
	if x != nil {
		return x.ProtoType
	}
	return DISP_PROTO_TYPE_HELLO
}

func (x *MsgDisp) GetTarget() DISP_MSG_TARGET {
	if x != nil {
		return x.Target
	}
	return DISP_MSG_TARGET_NON_SERVER
}

func (x *MsgDisp) GetMethod() DISP_MSG_METHOD {
	if x != nil {
		return x.Method
	}
	return DISP_MSG_METHOD_RAND
}

func (x *MsgDisp) GetSpecServer() int32 {
	if x != nil {
		return x.SpecServer
	}
	return 0
}

func (x *MsgDisp) GetFromServer() int32 {
	if x != nil {
		return x.FromServer
	}
	return 0
}

func (m *MsgDisp) GetDispBody() isMsgDisp_DispBody {
	if m != nil {
		return m.DispBody
	}
	return nil
}

func (x *MsgDisp) GetHello() *MsgDispHello {
	if x, ok := x.GetDispBody().(*MsgDisp_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *MsgDisp) GetKickDupUser() *MsgDispKickDupUser {
	if x, ok := x.GetDispBody().(*MsgDisp_KickDupUser); ok {
		return x.KickDupUser
	}
	return nil
}

type isMsgDisp_DispBody interface {
	isMsgDisp_DispBody()
}

type MsgDisp_Hello struct {
	Hello *MsgDispHello `protobuf:"bytes,20,opt,name=hello,proto3,oneof"`
}

type MsgDisp_KickDupUser struct {
	KickDupUser *MsgDispKickDupUser `protobuf:"bytes,21,opt,name=kick_dup_user,json=kickDupUser,proto3,oneof"`
}

func (*MsgDisp_Hello) isMsgDisp_DispBody() {}

func (*MsgDisp_KickDupUser) isMsgDisp_DispBody() {}

//*********DISP SUB MSG************
type MsgDispHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *MsgDispHello) Reset() {
	*x = MsgDispHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_disp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgDispHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDispHello) ProtoMessage() {}

func (x *MsgDispHello) ProtoReflect() protoreflect.Message {
	mi := &file_disp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDispHello.ProtoReflect.Descriptor instead.
func (*MsgDispHello) Descriptor() ([]byte, []int) {
	return file_disp_proto_rawDescGZIP(), []int{1}
}

func (x *MsgDispHello) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MsgDispKickDupUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetUid int64 `protobuf:"varint,1,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"` //target uid
}

func (x *MsgDispKickDupUser) Reset() {
	*x = MsgDispKickDupUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_disp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgDispKickDupUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDispKickDupUser) ProtoMessage() {}

func (x *MsgDispKickDupUser) ProtoReflect() protoreflect.Message {
	mi := &file_disp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDispKickDupUser.ProtoReflect.Descriptor instead.
func (*MsgDispKickDupUser) Descriptor() ([]byte, []int) {
	return file_disp_proto_rawDescGZIP(), []int{2}
}

func (x *MsgDispKickDupUser) GetTargetUid() int64 {
	if x != nil {
		return x.TargetUid
	}
	return 0
}

var File_disp_proto protoreflect.FileDescriptor

var file_disp_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x69, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x73, 0x73,
	0x22, 0xce, 0x02, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x69, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x73, 0x73, 0x2e, 0x44, 0x49, 0x53, 0x50, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x2b, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x73, 0x73, 0x2e, 0x44, 0x49, 0x53, 0x50, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x54,
	0x41, 0x52, 0x47, 0x45, 0x54, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x2b, 0x0a,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x73, 0x73, 0x2e, 0x44, 0x49, 0x53, 0x50, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x4d, 0x45, 0x54, 0x48,
	0x4f, 0x44, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x70,
	0x65, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x70, 0x65, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x66,
	0x72, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x05,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x73,
	0x2e, 0x4d, 0x73, 0x67, 0x44, 0x69, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52,
	0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x3c, 0x0a, 0x0d, 0x6b, 0x69, 0x63, 0x6b, 0x5f, 0x64,
	0x75, 0x70, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x73, 0x73, 0x2e, 0x4d, 0x73, 0x67, 0x44, 0x69, 0x73, 0x70, 0x4b, 0x69, 0x63, 0x6b, 0x44, 0x75,
	0x70, 0x55, 0x73, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x6b, 0x69, 0x63, 0x6b, 0x44, 0x75, 0x70,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x0b, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x70, 0x5f, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x28, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x44, 0x69, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x33, 0x0a, 0x12, 0x4d,
	0x73, 0x67, 0x44, 0x69, 0x73, 0x70, 0x4b, 0x69, 0x63, 0x6b, 0x44, 0x75, 0x70, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x69, 0x64,
	0x2a, 0x44, 0x0a, 0x0f, 0x44, 0x49, 0x53, 0x50, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x41, 0x52,
	0x47, 0x45, 0x54, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x4e, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45,
	0x52, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x4f, 0x47, 0x49, 0x43, 0x5f, 0x53, 0x45, 0x52,
	0x56, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x53, 0x45,
	0x52, 0x56, 0x45, 0x52, 0x10, 0x02, 0x2a, 0x2f, 0x0a, 0x0f, 0x44, 0x49, 0x53, 0x50, 0x5f, 0x4d,
	0x53, 0x47, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x41, 0x4e,
	0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x41, 0x53, 0x48, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x53, 0x50, 0x45, 0x43, 0x10, 0x02, 0x2a, 0x35, 0x0a, 0x0f, 0x44, 0x49, 0x53, 0x50, 0x5f,
	0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x45,
	0x4c, 0x4c, 0x4f, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4b, 0x49, 0x43, 0x4b, 0x5f, 0x44, 0x55,
	0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_disp_proto_rawDescOnce sync.Once
	file_disp_proto_rawDescData = file_disp_proto_rawDesc
)

func file_disp_proto_rawDescGZIP() []byte {
	file_disp_proto_rawDescOnce.Do(func() {
		file_disp_proto_rawDescData = protoimpl.X.CompressGZIP(file_disp_proto_rawDescData)
	})
	return file_disp_proto_rawDescData
}

var file_disp_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_disp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_disp_proto_goTypes = []interface{}{
	(DISP_MSG_TARGET)(0),       // 0: ss.DISP_MSG_TARGET
	(DISP_MSG_METHOD)(0),       // 1: ss.DISP_MSG_METHOD
	(DISP_PROTO_TYPE)(0),       // 2: ss.DISP_PROTO_TYPE
	(*MsgDisp)(nil),            // 3: ss.MsgDisp
	(*MsgDispHello)(nil),       // 4: ss.MsgDispHello
	(*MsgDispKickDupUser)(nil), // 5: ss.MsgDispKickDupUser
}
var file_disp_proto_depIdxs = []int32{
	2, // 0: ss.MsgDisp.proto_type:type_name -> ss.DISP_PROTO_TYPE
	0, // 1: ss.MsgDisp.target:type_name -> ss.DISP_MSG_TARGET
	1, // 2: ss.MsgDisp.method:type_name -> ss.DISP_MSG_METHOD
	4, // 3: ss.MsgDisp.hello:type_name -> ss.MsgDispHello
	5, // 4: ss.MsgDisp.kick_dup_user:type_name -> ss.MsgDispKickDupUser
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_disp_proto_init() }
func file_disp_proto_init() {
	if File_disp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_disp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgDisp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_disp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgDispHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_disp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgDispKickDupUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_disp_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*MsgDisp_Hello)(nil),
		(*MsgDisp_KickDupUser)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_disp_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_disp_proto_goTypes,
		DependencyIndexes: file_disp_proto_depIdxs,
		EnumInfos:         file_disp_proto_enumTypes,
		MessageInfos:      file_disp_proto_msgTypes,
	}.Build()
	File_disp_proto = out.File
	file_disp_proto_rawDesc = nil
	file_disp_proto_goTypes = nil
	file_disp_proto_depIdxs = nil
}
