// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: ss.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//proto type
type SS_PROTO_TYPE int32

const (
	SS_PROTO_TYPE_HEART_BEAT_REQ SS_PROTO_TYPE = 0
	SS_PROTO_TYPE_HEART_BEAT_RSP SS_PROTO_TYPE = 1
)

// Enum value maps for SS_PROTO_TYPE.
var (
	SS_PROTO_TYPE_name = map[int32]string{
		0: "HEART_BEAT_REQ",
		1: "HEART_BEAT_RSP",
	}
	SS_PROTO_TYPE_value = map[string]int32{
		"HEART_BEAT_REQ": 0,
		"HEART_BEAT_RSP": 1,
	}
)

func (x SS_PROTO_TYPE) Enum() *SS_PROTO_TYPE {
	p := new(SS_PROTO_TYPE)
	*p = x
	return p
}

func (x SS_PROTO_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SS_PROTO_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_ss_proto_enumTypes[0].Descriptor()
}

func (SS_PROTO_TYPE) Type() protoreflect.EnumType {
	return &file_ss_proto_enumTypes[0]
}

func (x SS_PROTO_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SS_PROTO_TYPE.Descriptor instead.
func (SS_PROTO_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_ss_proto_rawDescGZIP(), []int{0}
}

//main msg
type SSMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtoType SS_PROTO_TYPE `protobuf:"varint,1,opt,name=proto_type,json=protoType,proto3,enum=proto.SS_PROTO_TYPE" json:"proto_type,omitempty"`
	// Types that are assignable to MsgBody:
	//	*SSMsgReq_HeartBeat
	//	*SSMsgReq_Login
	MsgBody isSSMsgReq_MsgBody `protobuf_oneof:"msg_body"`
}

func (x *SSMsgReq) Reset() {
	*x = SSMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSMsgReq) ProtoMessage() {}

func (x *SSMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_ss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSMsgReq.ProtoReflect.Descriptor instead.
func (*SSMsgReq) Descriptor() ([]byte, []int) {
	return file_ss_proto_rawDescGZIP(), []int{0}
}

func (x *SSMsgReq) GetProtoType() SS_PROTO_TYPE {
	if x != nil {
		return x.ProtoType
	}
	return SS_PROTO_TYPE_HEART_BEAT_REQ
}

func (m *SSMsgReq) GetMsgBody() isSSMsgReq_MsgBody {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

func (x *SSMsgReq) GetHeartBeat() *MsgHeartBeatReq {
	if x, ok := x.GetMsgBody().(*SSMsgReq_HeartBeat); ok {
		return x.HeartBeat
	}
	return nil
}

func (x *SSMsgReq) GetLogin() *MsgLoginReq {
	if x, ok := x.GetMsgBody().(*SSMsgReq_Login); ok {
		return x.Login
	}
	return nil
}

type isSSMsgReq_MsgBody interface {
	isSSMsgReq_MsgBody()
}

type SSMsgReq_HeartBeat struct {
	HeartBeat *MsgHeartBeatReq `protobuf:"bytes,20,opt,name=heart_beat,json=heartBeat,proto3,oneof"`
}

type SSMsgReq_Login struct {
	Login *MsgLoginReq `protobuf:"bytes,21,opt,name=login,proto3,oneof"`
}

func (*SSMsgReq_HeartBeat) isSSMsgReq_MsgBody() {}

func (*SSMsgReq_Login) isSSMsgReq_MsgBody() {}

type SSMsgRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtoType SS_PROTO_TYPE `protobuf:"varint,1,opt,name=proto_type,json=protoType,proto3,enum=proto.SS_PROTO_TYPE" json:"proto_type,omitempty"`
	// Types that are assignable to MsgBody:
	//	*SSMsgRsp_Login
	MsgBody isSSMsgRsp_MsgBody `protobuf_oneof:"msg_body"`
}

func (x *SSMsgRsp) Reset() {
	*x = SSMsgRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSMsgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSMsgRsp) ProtoMessage() {}

func (x *SSMsgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSMsgRsp.ProtoReflect.Descriptor instead.
func (*SSMsgRsp) Descriptor() ([]byte, []int) {
	return file_ss_proto_rawDescGZIP(), []int{1}
}

func (x *SSMsgRsp) GetProtoType() SS_PROTO_TYPE {
	if x != nil {
		return x.ProtoType
	}
	return SS_PROTO_TYPE_HEART_BEAT_REQ
}

func (m *SSMsgRsp) GetMsgBody() isSSMsgRsp_MsgBody {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

func (x *SSMsgRsp) GetLogin() *MsgLoginRsp {
	if x, ok := x.GetMsgBody().(*SSMsgRsp_Login); ok {
		return x.Login
	}
	return nil
}

type isSSMsgRsp_MsgBody interface {
	isSSMsgRsp_MsgBody()
}

type SSMsgRsp_Login struct {
	Login *MsgLoginRsp `protobuf:"bytes,21,opt,name=login,proto3,oneof"`
}

func (*SSMsgRsp_Login) isSSMsgRsp_MsgBody() {}

//sub msg
type MsgHeartBeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts int64 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *MsgHeartBeatReq) Reset() {
	*x = MsgHeartBeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgHeartBeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHeartBeatReq) ProtoMessage() {}

func (x *MsgHeartBeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_ss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHeartBeatReq.ProtoReflect.Descriptor instead.
func (*MsgHeartBeatReq) Descriptor() ([]byte, []int) {
	return file_ss_proto_rawDescGZIP(), []int{2}
}

func (x *MsgHeartBeatReq) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type MsgLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MsgLoginReq) Reset() {
	*x = MsgLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoginReq) ProtoMessage() {}

func (x *MsgLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_ss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoginReq.ProtoReflect.Descriptor instead.
func (*MsgLoginReq) Descriptor() ([]byte, []int) {
	return file_ss_proto_rawDescGZIP(), []int{3}
}

func (x *MsgLoginReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MsgLoginReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MsgLoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Result bool  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MsgLoginRsp) Reset() {
	*x = MsgLoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoginRsp) ProtoMessage() {}

func (x *MsgLoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ss_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoginRsp.ProtoReflect.Descriptor instead.
func (*MsgLoginRsp) Descriptor() ([]byte, []int) {
	return file_ss_proto_rawDescGZIP(), []int{4}
}

func (x *MsgLoginRsp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MsgLoginRsp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_ss_proto protoreflect.FileDescriptor

var file_ss_proto_rawDesc = []byte{
	0x0a, 0x08, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb0, 0x01, 0x0a, 0x08, 0x53, 0x53, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x33,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x53, 0x5f, 0x50, 0x52,
	0x4f, 0x54, 0x4f, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x68, 0x65, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x65, 0x61,
	0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x73, 0x67, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x48,
	0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x2a, 0x0a, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x48,
	0x00, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f,
	0x62, 0x6f, 0x64, 0x79, 0x22, 0x77, 0x0a, 0x08, 0x53, 0x53, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70,
	0x12, 0x33, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x53, 0x5f,
	0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x73, 0x67,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x21, 0x0a,
	0x0f, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73,
	0x22, 0x33, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x37,
	0x0a, 0x0d, 0x53, 0x53, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12,
	0x12, 0x0a, 0x0e, 0x48, 0x45, 0x41, 0x52, 0x54, 0x5f, 0x42, 0x45, 0x41, 0x54, 0x5f, 0x52, 0x45,
	0x51, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x48, 0x45, 0x41, 0x52, 0x54, 0x5f, 0x42, 0x45, 0x41,
	0x54, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ss_proto_rawDescOnce sync.Once
	file_ss_proto_rawDescData = file_ss_proto_rawDesc
)

func file_ss_proto_rawDescGZIP() []byte {
	file_ss_proto_rawDescOnce.Do(func() {
		file_ss_proto_rawDescData = protoimpl.X.CompressGZIP(file_ss_proto_rawDescData)
	})
	return file_ss_proto_rawDescData
}

var file_ss_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ss_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ss_proto_goTypes = []interface{}{
	(SS_PROTO_TYPE)(0),      // 0: proto.SS_PROTO_TYPE
	(*SSMsgReq)(nil),        // 1: proto.SSMsgReq
	(*SSMsgRsp)(nil),        // 2: proto.SSMsgRsp
	(*MsgHeartBeatReq)(nil), // 3: proto.MsgHeartBeatReq
	(*MsgLoginReq)(nil),     // 4: proto.MsgLoginReq
	(*MsgLoginRsp)(nil),     // 5: proto.MsgLoginRsp
}
var file_ss_proto_depIdxs = []int32{
	0, // 0: proto.SSMsgReq.proto_type:type_name -> proto.SS_PROTO_TYPE
	3, // 1: proto.SSMsgReq.heart_beat:type_name -> proto.MsgHeartBeatReq
	4, // 2: proto.SSMsgReq.login:type_name -> proto.MsgLoginReq
	0, // 3: proto.SSMsgRsp.proto_type:type_name -> proto.SS_PROTO_TYPE
	5, // 4: proto.SSMsgRsp.login:type_name -> proto.MsgLoginRsp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ss_proto_init() }
func file_ss_proto_init() {
	if File_ss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSMsgRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgHeartBeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ss_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SSMsgReq_HeartBeat)(nil),
		(*SSMsgReq_Login)(nil),
	}
	file_ss_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SSMsgRsp_Login)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ss_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ss_proto_goTypes,
		DependencyIndexes: file_ss_proto_depIdxs,
		EnumInfos:         file_ss_proto_enumTypes,
		MessageInfos:      file_ss_proto_msgTypes,
	}.Build()
	File_ss_proto = out.File
	file_ss_proto_rawDesc = nil
	file_ss_proto_goTypes = nil
	file_ss_proto_depIdxs = nil
}
